

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBlock;
                ref class Button;
                ref class Image;
            }
        }
    }
}

namespace App2
{
    partial ref class Stage3 : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtTitle;
        private: ::Windows::UI::Xaml::Controls::Button^ btnBackP3;
        private: ::Windows::UI::Xaml::Controls::Image^ imgBox3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtCode3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtExpl3;
        private: ::Windows::UI::Xaml::Controls::Button^ btnResult;
    };
}

