

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBlock;
                ref class Image;
                ref class Button;
            }
        }
    }
}

namespace App2
{
    partial ref class Stage1 : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtTitle;
        private: ::Windows::UI::Xaml::Controls::Image^ imgBox;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtCode;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtExpl;
        private: ::Windows::UI::Xaml::Controls::Button^ btnBackP1;
    };
}

