

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBlock;
                ref class Button;
                ref class Image;
            }
        }
    }
}

namespace App2
{
    partial ref class Stage2 : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtTitle;
        private: ::Windows::UI::Xaml::Controls::Button^ btnStage3;
        private: ::Windows::UI::Xaml::Controls::Button^ btn1;
        private: ::Windows::UI::Xaml::Controls::Button^ btn2;
        private: ::Windows::UI::Xaml::Controls::Button^ btn3;
        private: ::Windows::UI::Xaml::Controls::Image^ imgBox2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtCode2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtExpl2;
        private: ::Windows::UI::Xaml::Controls::Button^ btnBackP2;
        private: ::Windows::UI::Xaml::Controls::Button^ btnE1;
        private: ::Windows::UI::Xaml::Controls::Button^ btnE2;
        private: ::Windows::UI::Xaml::Controls::Button^ btnE3;
        private: ::Windows::UI::Xaml::Controls::Button^ btnE4;
        private: ::Windows::UI::Xaml::Controls::Button^ btnE5;
        private: ::Windows::UI::Xaml::Controls::Button^ btnE6;
        private: ::Windows::UI::Xaml::Controls::Button^ btnE7;
        private: ::Windows::UI::Xaml::Controls::Button^ btnE8;
        private: ::Windows::UI::Xaml::Controls::Button^ btnE9;
        private: ::Windows::UI::Xaml::Controls::Button^ btnE10;
        private: ::Windows::UI::Xaml::Controls::Button^ btnE11;
        private: ::Windows::UI::Xaml::Controls::Button^ btnE12;
    };
}

